### PR TITLE
Feat/test ci

### PR DESCRIPTION
**Pull request by gibertif**
Dear all,

included linting, and support for clang-5.0. As for Travis, clang works fine, but with g++ a CXX compiler. if I use clang and libstdc++ I got errors. I was not able to solve the problem, so if anyone with experience in clang want to help me on this, more than happy! :D 

I am working on the macos test, hope to be able to create it before next meeting.

### CODE REVIEW

**Comment by felixmusil** [comment]
I am not sure I understand you on clang. I see that you compile with clang with:
```
cmake -DCMAKE_C_COMPILER=clang-5.0 ..
```
while to really test the compilation with clang compiler would require:
```
cmake -DCMAKE_C_COMPILER=clang-5.0 -DCMAKE_CXX_COMPILER=clang++-5.0 ..
```
Is it the problem you are mentioning ?

**Comment by mastricker** [comment]
I also do not understand.
And is "Travis" your name for Circle I, or are we back von TravisCI?

On Dec 6, 2018 17:17, gibertif <notifications@github.com> wrote:

Dear all,

included linting, and support for clang-5.0. As for Travis, clang works fine, but with g++ a CXX compiler. if I use clang and libstdc++ I got errors. I was not able to solve the problem, so if anyone with experience in clang want to help me on this, more than happy! :D

I am working on the macos test, hope to be able to create it before next meeting.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/cosmo-epfl/librascal/pull/53

Commit Summary

  *   testing clang and g++ workflow
  *   testing macos
  *   typo
  *   clang and g++ working

File Changes

  *   M .circleci/config.yml<https://github.com/cosmo-epfl/librascal/pull/53/files#diff-0> (74)
  *   D .circleci/config_multi_jobs.yml<https://github.com/cosmo-epfl/librascal/pull/53/files#diff-1> (67)
  *   D .circleci/config_no_workflow.yml<https://github.com/cosmo-epfl/librascal/pull/53/files#diff-2> (60)
  *   R .circleci/config_ubuntu_clang.yml<https://github.com/cosmo-epfl/librascal/pull/53/files#diff-3> (32)
  *   R .circleci/config_ubuntu_g++.yml<https://github.com/cosmo-epfl/librascal/pull/53/files#diff-4> (18)

Patch Links:

  *   https://github.com/cosmo-epfl/librascal/pull/53.patch
  *   https://github.com/cosmo-epfl/librascal/pull/53.diff

-

**Comment by gibertif** [comment]
So,

When I did this on circleci local, compiling and linking w clang-5.0 was throwing this error

`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

However, on the remote server works fine. So forget my previous commment, it is now working with clang-5.0 and GNU compiler 7.3

Will work on MacOS asap

**Comment by felixmusil** [comment]
Could you also add GCC 5 and clang 7 ? So that we cover oldish and brand new compilers. They tend to not get the same errors xd

**Comment by felixmusil** [comment]
so make sure not to use the c compiler for the c++:
```
-DCMAKE_CXX_COMPILER=clang-7
```
should be:
```
-DCMAKE_CXX_COMPILER=clang++-7
```

**Pull request merged**
